### ISSUE TITLE
The Auto install is not working

### ISSUE THREAD

**Issue by henryfalon** [creptor/atom.cms-With_auto_installer#1]
Thank You taking time to make the auto install but it is not working 
after i added dbconnection it showed another error on the data.php 
actually after i fixed that another came up in setup.php  errors keep coming up
I understand when you said you dont encourage laziness but at least you would have added comments
It looks as if you were forced to do so please can you post the ones with comments or a read me file so that people like us that dont have the privileges you have to learn in this part of the world can at least learn from Good Teachers like you. that tutorial by digicraft was wonderful. Keep Up the good work. if i have money i would have donated to you. Thank You

**Comment by henryfalon** [comment]
finally i figured out that the i have to run instal instead of running through index.php
the cms started well then i got this error Cannot create file ($filename). please what is the variable  ($filename). and what can i do to solve the issue i ham still going through the files trying to find it . please help

if(!$handle=fopen($filename,'w')){
    $output=json_encode(array('type'=>'error','text'=>'Cannot create file ($filename).'));
    die($output);

**Comment by creptor** [comment]
Oh I understand, I might have change the setup process in the testing, because it should redirect you to the install from the index.php.

The other thing I'll look into it when I have my computer.
will update soon 😝
